yarnPath: .yarn/releases/yarn-3.5.1.cjs
nodeLinker: node-modules

npmScopes:
  projitect:
    npmRegistryServer: https://npm.pkg.github.com

npmRegistries:
  //npm.pkg.github.com/:
    npmAuthToken: ${GITHUB_PACKAGES_PROJITECT_AUTH_TOKEN}
